name: Auto-merge Claude PRs

on:
  pull_request_target:
    types: [opened, synchronize]
    branches:
      - claude_bot

jobs:
  auto-approve-and-merge:
    # Solo para PRs creados por claude[bot] hacia claude_bot
    if: |
      github.event.pull_request.user.login == 'claude[bot]' &&
      github.event.pull_request.base.ref == 'claude_bot'

    runs-on: ubuntu-latest

    permissions:
      pull-requests: write
      contents: write

    steps:
      - name: Auto-approve PR
        uses: hmarr/auto-approve-action@v4
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}

      - name: Enable auto-merge
        run: |
          gh pr merge --auto --squash "${{ github.event.pull_request.number }}"
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GH_REPO: ${{ github.repository }}
