name: Claude Bot Automation

on:
  issues:
    types: [opened, edited]

jobs:
  claude-job:
    runs-on: ubuntu-latest
    timeout-minutes: 30

    permissions:
      contents: write
      pull-requests: write
      issues: write
      id-token: write
      actions: read  # Required for Claude to read CI results

    steps:
      - name: Checkout claude_bot branch
        uses: actions/checkout@v4
        with:
          ref: claude_bot
          fetch-depth: 0

      - name: Run Claude Code
        uses: anthropics/claude-code-action@v1
        with:
          # Rama base siempre será claude_bot
          base_branch: claude_bot

          # Prefijo para ramas creadas por Claude
          branch_prefix: "claude-bot/"

          # Se activa sin necesidad de @claude (string vacío = siempre activo)
          trigger_phrase: ""

          # Autenticación con API Key de Anthropic
          anthropic_api_key: ${{ secrets.ANTHROPIC_API_KEY }}

          # Prompt personalizado que indica trabajar solo en claude_bot
          prompt: |
            IMPORTANT: You MUST ONLY work on the 'claude_bot' branch.
            - Always create branches from 'claude_bot'
            - Never modify main, master, or any other branch
            - All changes must target the 'claude_bot' branch
            - Create pull requests against 'claude_bot' only

            Now, address the issue or request provided.
