name: Claude Bot Automation

on:
  issues:
    types: [opened, edited]
  issue_comment:
    types: [created]

jobs:
  claude-job:
    # Solo ejecutar si el comentario contiene @claude, o si es un issue nuevo/editado
    if: |
      github.event_name == 'issues' ||
      (github.event_name == 'issue_comment' && contains(github.event.comment.body, '@claude'))

    runs-on: ubuntu-latest
    timeout-minutes: 30

    permissions:
      contents: write
      pull-requests: write
      issues: write
      id-token: write
      actions: read  # Required for Claude to read CI results

    steps:
      - name: Checkout claude_bot branch
        uses: actions/checkout@v4
        with:
          ref: claude_bot
          fetch-depth: 0

      - name: Run Claude Code
        uses: anthropics/claude-code-action@v1
        with:
          # Rama base siempre será claude_bot
          base_branch: claude_bot

          # Trigger cuando se menciona @claude en el issue
          trigger_phrase: "@claude"

          # Autenticación con OAuth token de Claude Max
          claude_code_oauth_token: ${{ secrets.CLAUDE_CODE_OAUTH_TOKEN }}

          # Prompt personalizado: commit directo sin PRs
          prompt: |
            REPOSITORY: ${{ github.repository }}
            ISSUE NUMBER: ${{ github.event.issue.number }}
            ISSUE TITLE: ${{ github.event.issue.title }}
            ISSUE BODY: ${{ github.event.issue.body }}
            COMMENT: ${{ github.event.comment.body }}

            IMPORTANT: You have FULL CONTROL over the 'claude_bot' branch.
            - Work directly on 'claude_bot' branch
            - Make commits directly to 'claude_bot' (NO pull requests)
            - Push changes directly to 'claude_bot'
            - Never modify main, master, or any other branch

            WORKFLOW:
            1. Analyze the issue/comment and implement the solution
            2. Make commits directly to 'claude_bot'
            3. Add a comment to the issue summarizing what you did
            4. Close the issue when completed

            Now, address the request in the ISSUE TITLE, ISSUE BODY, or COMMENT above.
