name: Deploy

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to server
        uses: appleboy/ssh-action@v0.1.8
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: ${{ secrets.SERVER_PORT }}
          script: |
            export SHELL=/bin/zsh
            source ~/.zshrc
            export NVM_DIR="$HOME/.nvm"
            [ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"
            [ -s "$NVM_DIR/bash_completion" ] && \. "$NVM_DIR/bash_completion"
            cd ${{ secrets.DEPLOY_PATH }}/mappertrip.com
            git fetch --all
            git reset --hard origin/main
            npm install
            npm run build
            pm2 flush
            pm2 startOrRestart ecosystem.config.js --update-env

      - name: Send Pushcut notification
        run: |
          curl -X POST "https://api.pushcut.io/eOU0kCDr2y95dXanO0nwk/notifications/Deploy" \
            -H "Content-Type: application/json" \
            -d '{"title": "Deploy finished - '${{ github.repository }}'"}'