name: Reopen Improvements Issue

on:
  schedule:
    # Ejecutar cada 4 horas
    - cron: '0 */4 * * *'
  workflow_dispatch: # Permite ejecución manual

jobs:
  reopen-issue:
    runs-on: ubuntu-latest

    permissions:
      issues: write

    steps:
      - name: Find Improvements issue
        id: find_issue
        run: |
          # Buscar el issue por título "Improvements" (incluyendo cerrados)
          ISSUE_NUMBER=$(gh issue list --repo ${{ github.repository }} --state all --search "Improvements in:title" --json number --jq '.[0].number')

          if [ -z "$ISSUE_NUMBER" ]; then
            echo "No se encontró issue con título 'Improvements'"
            exit 1
          fi

          echo "issue_number=$ISSUE_NUMBER" >> $GITHUB_OUTPUT
          echo "Encontrado issue #$ISSUE_NUMBER"
        env:
          GH_TOKEN: ${{ secrets.PERSONAL_GITHUB_ACCESS_TOKEN }}

      - name: Close Improvements issue first
        run: |
          gh issue close ${{ steps.find_issue.outputs.issue_number }} --repo ${{ github.repository }} || true
        env:
          GH_TOKEN: ${{ secrets.PERSONAL_GITHUB_ACCESS_TOKEN }}

      - name: Reopen Improvements issue
        run: |
          gh issue reopen ${{ steps.find_issue.outputs.issue_number }} --repo ${{ github.repository }}
        env:
          GH_TOKEN: ${{ secrets.PERSONAL_GITHUB_ACCESS_TOKEN }}
